[package]
name = "icp_vr_genesis_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.12.3"
candid = "0.10.0"
serde = { version = "1.0", features = ["derive"] }
